"""
Deterministic DSL -> LangGraph code compiler.

NO LLM is used here. Given the same SystemSpec, this always emits byte-identical
Python. That property is what makes generated systems debuggable and trustworthy:
the LLM's creativity is confined to producing the DSL; turning DSL into code is
pure, testable machinery.

The generated module exposes `build_graph()` returning a compiled LangGraph app
with a SQLite checkpointer, plus a `__main__` block for quick local runs.
"""
from __future__ import annotations

from textwrap import indent

from ..dsl.schema import END, SystemSpec


def _agent_node_fn(spec: SystemSpec, agent) -> str:
    model = agent.model or spec.llm.model
    tools_repr = ", ".join(repr(t) for t in agent.tools)
    return f'''
def agent_{agent.id}(state: State) -> dict:
    """{agent.role}"""
    llm = make_llm(model={model!r})
    tools = resolve_tools([{tools_repr}])
    messages = build_messages(
        role={agent.role!r},
        memory_kind={agent.memory.value!r},
        agent_id={agent.id!r},
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {{"messages": state["messages"] + [result["message"]],
            "scratch": {{**state.get("scratch", {{}}), {agent.id!r}: result["output"]}},
            "last_agent": {agent.id!r}}}
'''


def _router_fns(spec: SystemSpec) -> str:
    """Emit one router per source node that has conditional edges."""
    by_source: dict[str, list] = {}
    for e in spec.graph.edges:
        by_source.setdefault(e.from_, []).append(e)

    out = []
    for source, edges in by_source.items():
        conditional = [e for e in edges if e.condition]
        if not conditional:
            continue
        # Map condition string -> target. Last-resort fallback to END.
        mapping = {e.condition: e.to for e in conditional}
        unconditional = [e for e in edges if not e.condition]
        default = unconditional[0].to if unconditional else END
        out.append(f'''
def route_{source}(state: State) -> str:
    decision = (state.get("scratch", {{}}).get({source!r}, {{}}) or {{}})
    signal = decision.get("route") if isinstance(decision, dict) else None
    mapping = {mapping!r}
    return mapping.get(signal, {default!r})
''')
    return "\n".join(out)


def _graph_wiring(spec: SystemSpec) -> str:
    lines = ["    g = StateGraph(State)"]
    for a in spec.agents:
        lines.append(f"    g.add_node({a.id!r}, agent_{a.id})")
    lines.append(f"    g.set_entry_point({spec.graph.entry!r})")

    by_source: dict[str, list] = {}
    for e in spec.graph.edges:
        by_source.setdefault(e.from_, []).append(e)

    for source, edges in by_source.items():
        has_conditional = any(e.condition for e in edges)
        if has_conditional:
            # The router returns a destination node name (a string). The path map
            # keys are those return values; the values are the actual graph
            # destinations (node-name string, or the END constant).
            targets = sorted({e.to for e in edges})
            pairs = []
            for t in targets:
                value = "END" if t == END else repr(t)   # END constant vs node str
                pairs.append(f"{t!r}: {value}")
            lines.append(
                f"    g.add_conditional_edges({source!r}, route_{source}, "
                f"{{{', '.join(pairs)}}})"
            )
        else:
            for e in edges:
                tgt = "END" if e.to == END else repr(e.to)
                lines.append(f"    g.add_edge({source!r}, {tgt})")
    return "\n".join(lines)


END_CONST = "END"  # how END is referenced in generated wiring


def compile_spec(spec: SystemSpec) -> str:
    if spec.runtime.value != "langgraph":
        raise NotImplementedError(
            f"runtime '{spec.runtime.value}' not supported yet (langgraph only)"
        )

    nodes = "\n".join(_agent_node_fn(spec, a) for a in spec.agents)
    routers = _router_fns(spec)
    wiring = _graph_wiring(spec)

    header = f'''"""
AUTO-GENERATED by AgentForge. Do not edit by hand.
System: {spec.name}
Runtime: langgraph
Regenerate by editing the DSL and recompiling.
"""
from typing import Annotated, TypedDict
import operator

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver

from agentforge.runtime.support import make_llm, resolve_tools, build_messages, run_agent


class State(TypedDict):
    messages: Annotated[list, operator.add]
    scratch: dict
    last_agent: str
'''

    builder = f'''
def build_graph(checkpoint_path: str = "agentforge/checkpoints/{spec.name}.sqlite"):
{indent(wiring, "")}
    import sqlite3
    conn = sqlite3.connect(checkpoint_path, check_same_thread=False)
    saver = SqliteSaver(conn)
    return g.compile(checkpointer=saver)


def run(prompt: str, thread_id: str = "default") -> dict:
    app = build_graph()
    config = {{"configurable": {{"thread_id": thread_id}}}}
    init = {{"messages": [{{"role": "user", "content": prompt}}],
            "scratch": {{}}, "last_agent": ""}}
    return app.invoke(init, config=config)


if __name__ == "__main__":
    import sys
    prompt = sys.argv[1] if len(sys.argv) > 1 else "Hello"
    out = run(prompt)
    print(out["messages"][-1])
'''

    return header + "\n" + nodes + "\n" + routers + "\n" + builder
