"""
AUTO-GENERATED by AgentForge. Do not edit by hand.
System: automate_the_initial_screening_and_routi
Runtime: langgraph
Regenerate by editing the DSL and recompiling.
"""
from typing import Annotated, TypedDict
import operator

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver

from agentforge.runtime.support import make_llm, resolve_tools, build_messages, run_agent


class State(TypedDict):
    messages: Annotated[list, operator.add]
    scratch: dict
    last_agent: str


def agent_iterator(state: State) -> dict:
    """Reads the work queue and decides whether to continue processing the batch or finish the entire job."""
    llm = make_llm(model='qwen2.5:14b')
    tools = resolve_tools([])
    messages = build_messages(
        role='Reads the work queue and decides whether to continue processing the batch or finish the entire job.',
        memory_kind='none',
        agent_id='iterator',
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {"messages": state["messages"] + [result["message"]],
            "scratch": {**state.get("scratch", {}), 'iterator': result["output"]},
            "last_agent": 'iterator'}


def agent_parser(state: State) -> dict:
    """Extracts structured data (experience and skills) from the unstructured PDF job application documents."""
    llm = make_llm(model='qwen2.5:14b')
    tools = resolve_tools([])
    messages = build_messages(
        role='Extracts structured data (experience and skills) from the unstructured PDF job application documents.',
        memory_kind='none',
        agent_id='parser',
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {"messages": state["messages"] + [result["message"]],
            "scratch": {**state.get("scratch", {}), 'parser': result["output"]},
            "last_agent": 'parser'}


def agent_scorer(state: State) -> dict:
    """Compares extracted candidate skills against the required skill list and calculates a percentage match score."""
    llm = make_llm(model='qwen2.5:14b')
    tools = resolve_tools([])
    messages = build_messages(
        role='Compares extracted candidate skills against the required skill list and calculates a percentage match score.',
        memory_kind='none',
        agent_id='scorer',
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {"messages": state["messages"] + [result["message"]],
            "scratch": {**state.get("scratch", {}), 'scorer': result["output"]},
            "last_agent": 'scorer'}


def agent_router(state: State) -> dict:
    """Determines the next processing step (Forward, Maybe, Reject) based on experience and skill scores, emitting 'ROUTE: <signal>' for each outcome."""
    llm = make_llm(model='qwen2.5:14b')
    tools = resolve_tools([])
    messages = build_messages(
        role="Determines the next processing step (Forward, Maybe, Reject) based on experience and skill scores, emitting 'ROUTE: <signal>' for each outcome.",
        memory_kind='none',
        agent_id='router',
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {"messages": state["messages"] + [result["message"]],
            "scratch": {**state.get("scratch", {}), 'router': result["output"]},
            "last_agent": 'router'}


def agent_reject_handler(state: State) -> dict:
    """Generates and sends a templated rejection email for candidates failing the experience or skill thresholds."""
    llm = make_llm(model='qwen2.5:14b')
    tools = resolve_tools([])
    messages = build_messages(
        role='Generates and sends a templated rejection email for candidates failing the experience or skill thresholds.',
        memory_kind='none',
        agent_id='reject_handler',
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {"messages": state["messages"] + [result["message"]],
            "scratch": {**state.get("scratch", {}), 'reject_handler': result["output"]},
            "last_agent": 'reject_handler'}


def agent_queue_manager(state: State) -> dict:
    """Updates the running counts and routes the candidate to the appropriate queue (Forwarded, Maybe, Rejected)."""
    llm = make_llm(model='qwen2.5:14b')
    tools = resolve_tools([])
    messages = build_messages(
        role='Updates the running counts and routes the candidate to the appropriate queue (Forwarded, Maybe, Rejected).',
        memory_kind='none',
        agent_id='queue_manager',
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {"messages": state["messages"] + [result["message"]],
            "scratch": {**state.get("scratch", {}), 'queue_manager': result["output"]},
            "last_agent": 'queue_manager'}


def agent_reporter(state: State) -> dict:
    """Generates the final summary report detailing the processing outcomes once all applications have been processed."""
    llm = make_llm(model='qwen2.5:14b')
    tools = resolve_tools([])
    messages = build_messages(
        role='Generates the final summary report detailing the processing outcomes once all applications have been processed.',
        memory_kind='none',
        agent_id='reporter',
        state=state,
    )
    result = run_agent(llm, tools, messages, state)
    return {"messages": state["messages"] + [result["message"]],
            "scratch": {**state.get("scratch", {}), 'reporter': result["output"]},
            "last_agent": 'reporter'}


def route_iterator(state: State) -> str:
    decision = (state.get("scratch", {}).get('iterator', {}) or {})
    signal = decision.get("route") if isinstance(decision, dict) else None
    mapping = {'continue': 'parser', 'finish': 'reporter'}
    return mapping.get(signal, 'END')


def route_router(state: State) -> str:
    decision = (state.get("scratch", {}).get('router', {}) or {})
    signal = decision.get("route") if isinstance(decision, dict) else None
    mapping = {'forward': 'queue_manager', 'maybe': 'queue_manager', 'reject': 'reject_handler'}
    return mapping.get(signal, 'END')


def build_graph(checkpoint_path: str = "agentforge/checkpoints/automate_the_initial_screening_and_routi.sqlite"):
    g = StateGraph(State)
    g.add_node('iterator', agent_iterator)
    g.add_node('parser', agent_parser)
    g.add_node('scorer', agent_scorer)
    g.add_node('router', agent_router)
    g.add_node('reject_handler', agent_reject_handler)
    g.add_node('queue_manager', agent_queue_manager)
    g.add_node('reporter', agent_reporter)
    g.set_entry_point('iterator')
    g.add_conditional_edges('iterator', route_iterator, {'parser': 'parser', 'reporter': 'reporter'})
    g.add_edge('parser', 'scorer')
    g.add_edge('scorer', 'router')
    g.add_conditional_edges('router', route_router, {'queue_manager': 'queue_manager', 'reject_handler': 'reject_handler'})
    g.add_edge('reject_handler', 'iterator')
    g.add_edge('queue_manager', 'iterator')
    g.add_edge('reporter', END)
    import sqlite3
    conn = sqlite3.connect(checkpoint_path, check_same_thread=False)
    saver = SqliteSaver(conn)
    return g.compile(checkpointer=saver)


def run(prompt: str, thread_id: str = "default") -> dict:
    app = build_graph()
    config = {"configurable": {"thread_id": thread_id}}
    init = {"messages": [{"role": "user", "content": prompt}],
            "scratch": {}, "last_agent": ""}
    return app.invoke(init, config=config)


if __name__ == "__main__":
    import sys
    prompt = sys.argv[1] if len(sys.argv) > 1 else "Hello"
    out = run(prompt)
    print(out["messages"][-1])
